// Generated by FlutterFire CLI + manual merge.
// Firebase project: teary-app (tangza@gmail.com)

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDttA_YyTP1TgVOT1O7FF4d2MRlwCA2pwQ',
    appId: '1:592518994303:web:26115a07fa5c58ca08a24a',
    messagingSenderId: '592518994303',
    projectId: 'teary-app',
    authDomain: 'teary-app.firebaseapp.com',
    storageBucket: 'teary-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3C4vhlGW8Uw2Inv01uZm4Y84zONGHmOs',
    appId: '1:592518994303:android:30cdebe096521ba108a24a',
    messagingSenderId: '592518994303',
    projectId: 'teary-app',
    storageBucket: 'teary-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxmwuKwLXNDI4Dc0oFdAQQ9gyDnBuTKFc',
    appId: '1:592518994303:ios:3f0f3564d88c0f6c08a24a',
    messagingSenderId: '592518994303',
    projectId: 'teary-app',
    storageBucket: 'teary-app.firebasestorage.app',
    iosBundleId: 'com.tangza.teary',
  );
}
